// Clay configuration page. The battery-stats text block is filled in
// dynamically by index.js (see BATTERY_STATS_PLACEHOLDER) right before the
// page is opened, so it shows live values from the watch.

// version.js is auto-generated by wscript at build time.
var versionInfo = (function () {
  try { return require('./version'); }
  catch (e) { return { version: '0.0.0', buildDate: 'unknown' }; }
})();

// "HH:00" select options for the night window pickers.
function hourOptions() {
  var opts = [];
  for (var h = 0; h < 24; h++) {
    opts.push({
      "label": (h < 10 ? "0" + h : "" + h) + ":00",
      "value": "" + h
    });
  }
  return opts;
}

module.exports = [
  {
    "type": "heading",
    "defaultValue": "Pebblesole Settings"
  },
  {
    "type": "section",
    "items": [
      {
        "type": "heading",
        "defaultValue": "Weather"
      },
      {
        "type": "radiogroup",
        "messageKey": "TEMP_UNITS",
        "label": "Temperature units",
        "defaultValue": "0",
        "options": [
          { "label": "Celsius (°C)", "value": "0" },
          { "label": "Fahrenheit (°F)", "value": "1" }
        ]
      },
      {
        "type": "select",
        "messageKey": "WEATHER_INTERVAL",
        "label": "Weather refresh",
        "defaultValue": "30",
        "options": [
          { "label": "Every 15 minutes", "value": "15" },
          { "label": "Every 30 minutes", "value": "30" },
          { "label": "Every hour", "value": "60" },
          { "label": "Every 2 hours", "value": "120" },
          { "label": "Every 6 hours", "value": "360" }
        ]
      }
    ]
  },
  {
    "type": "section",
    "items": [
      {
        "type": "heading",
        "defaultValue": "Night idle mode"
      },
      {
        "type": "toggle",
        "messageKey": "NIGHT_MODE_ENABLED",
        "label": "Night idle mode",
        "defaultValue": false,
        "description": "After 20 minutes without wrist movement during your night window, the watchface slows display and health updates and pauses weather refreshes. Shaking your wrist wakes it back up immediately."
      },
      {
        "type": "select",
        "messageKey": "NIGHT_START_HOUR",
        "label": "Start",
        "defaultValue": "0",
        "options": hourOptions()
      },
      {
        "type": "select",
        "messageKey": "NIGHT_END_HOUR",
        "label": "End",
        "defaultValue": "6",
        "options": hourOptions()
      },
      {
        "type": "select",
        "messageKey": "NIGHT_UPDATE_INTERVAL",
        "label": "Update cadence",
        "defaultValue": "5",
        "options": [
          { "label": "Every 3 minutes", "value": "3" },
          { "label": "Every 5 minutes", "value": "5" },
          { "label": "Every 10 minutes", "value": "10" },
          { "label": "Every 15 minutes", "value": "15" }
        ]
      }
    ]
  },
  {
    "type": "section",
    "items": [
      {
        "type": "heading",
        "defaultValue": "Display"
      },
      {
        "type": "select",
        "messageKey": "BACKLIGHT_COLOR",
        "label": "Backlight colour",
        "defaultValue": "0",
        "description": "Tints the backlight LED (Pebble Time 2 RGB backlight).",
        "options": [
          { "label": "System Default", "value": "0" },
          { "label": "White", "value": "1" },
          { "label": "YInMn Blue", "value": "2" },
          { "label": "Red", "value": "3" },
          { "label": "Amber", "value": "4" },
          { "label": "Yellow", "value": "5" },
          { "label": "Green", "value": "6" }
        ]
      }
    ]
  },
  {
    "type": "section",
    "items": [
      {
        "type": "heading",
        "defaultValue": "Battery Stats"
      },
      {
        "type": "text",
        "id": "batteryStats",
        "defaultValue": "BATTERY_STATS_PLACEHOLDER"
      }
    ]
  },
  {
    "type": "section",
    "items": [
      {
        "type": "heading",
        "defaultValue": "About"
      },
      {
        "type": "text",
        "defaultValue": "Version: <strong>" + versionInfo.version + "</strong><br>" +
                        "Build date: <strong>" + versionInfo.buildDate + "</strong>"
      }
    ]
  },
  {
    "type": "submit",
    "defaultValue": "Save"
  }
];
